services:
  web:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    container_name: web
    restart: always
    command: sh -c "chmod +x ./scripts/wait-for-it.sh ; ./scripts/wait-for-it.sh db:5432 -- npm run build && python app/manage.py collectstatic --no-input && python app/manage.py makemigrations && python app/manage.py migrate && python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../../app:/home/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  celery:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    restart: always
    container_name: celery
    command: celery -A app.config worker --loglevel=info
    volumes:
      - ../../app:/home/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    restart: always
    container_name: celery-beat
    command: celery -A app.config beat --loglevel=info
    volumes:
      - ../../app:/home/app
    env_file:
      - ./.env
    depends_on:
      - celery
      - redis

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379

volumes:
  postgres_data: