# Generated by Django 5.0.3 on 2024-04-09 15:48

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Enter a username in lowercase containing 4-20 characters. It can only contain letters, hyphens, and digits.', max_length=20, unique=True, validators=[apps.accounts.validators.validate_username], verbose_name='username'),
        ),
    ]
