# Generated by Django 5.0.3 on 2024-04-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_candle_options_alter_candle_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='price_change', serialize=False, to='stocks.stock', verbose_name='stock')),
                ('value_per_day', models.DecimalField(decimal_places=18, max_digits=36, verbose_name='value per day')),
                ('percent_per_day', models.DecimalField(decimal_places=18, max_digits=36, verbose_name='percent per day')),
                ('value_per_year', models.DecimalField(decimal_places=18, max_digits=36, verbose_name='value per year')),
                ('percent_per_year', models.DecimalField(decimal_places=18, max_digits=36, verbose_name='percent per year')),
            ],
            options={
                'verbose_name': 'Price Change',
                'verbose_name_plural': 'Price Changes',
            },
        ),
    ]
