# Generated by Django 5.0.3 on 2024-05-03 16:43

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_favourite_stock_blacklistedstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='time_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(db_index=True, help_text='The time range during which the candlestick represents the trading activity.', verbose_name='time range'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(db_index=True, help_text='The ticker of the stock.', max_length=10, primary_key=True, serialize=False, verbose_name='ticker'),
        ),
    ]
