# Generated by Django 5.0.3 on 2024-03-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(help_text='The ticker of the stock.', max_length=10, primary_key=True, serialize=False, verbose_name='ticker')),
                ('shortname', models.CharField(help_text='The short name of the instrument.', max_length=50, null=True, verbose_name='short name')),
                ('secname', models.CharField(help_text='The name of the financial instrument.', max_length=50, null=True, verbose_name='secname')),
                ('latname', models.CharField(help_text='The name of the financial instrument in English.', max_length=50, null=True, verbose_name='latname')),
                ('prevprice', models.DecimalField(decimal_places=10, default=0, help_text='The price of the last trade of the previous day.', max_digits=20, null=True, verbose_name='prevprice')),
                ('lotsize', models.PositiveIntegerField(help_text='The number of securities in one standard lot.', null=True, verbose_name='lotsize')),
                ('facevalue', models.DecimalField(decimal_places=17, help_text='The nominal value of one security at the current date.', max_digits=34, null=True, verbose_name='facevalue')),
                ('faceunit', models.CharField(help_text='The code of the currency in which the nominal value of the security is expressed.', max_length=10, null=True, verbose_name='faceunit')),
                ('status', models.CharField(choices=[('A', 'Operations are allowed'), ('S', 'Operations are prohibited'), ('N', 'Blocked for trading, execution of transactions is allowed')], default='A', help_text='The indicator "trading operations are allowed/prohibited".', max_length=1, null=True, verbose_name='status')),
                ('decimals', models.PositiveSmallIntegerField(default=0, help_text='The number of decimal places of the fractional part of the number. It is used to format the values of fields with the DECIMAL type.', null=True, verbose_name='decimals')),
                ('minstep', models.DecimalField(decimal_places=10, help_text='The minimum possible difference between the prices indicated in the bids for the purchase/sale of securities', max_digits=20, null=True, verbose_name='min step')),
                ('prevdate', models.DateField(help_text='The date of the previous trading day.', null=True, verbose_name='prevdate')),
                ('issuesize', models.PositiveBigIntegerField(help_text='The number of securities in the issue.', null=True, verbose_name='issuesize')),
                ('isin', models.CharField(help_text='The international identification code of the security.', max_length=20, null=True, verbose_name='isin')),
                ('regnumber', models.CharField(help_text='The number of the state registration.', max_length=50, null=True, verbose_name='regnumber')),
                ('prevlegalcloseprice', models.DecimalField(decimal_places=10, default=0, help_text='The official closing price of the previous day, calculated in accordance with the trading rules as the weighted average price of transactions for the last 10 minutes of the main session, including transactions of the post-trading period or the closing auction.', max_digits=20, null=True, verbose_name='prev legal close price')),
                ('currencyid', models.CharField(help_text='The currency of settlement for the instrument.', max_length=10, null=True, verbose_name='currency ID')),
                ('sectype', models.CharField(choices=[('1', 'The security is ordinary'), ('2', 'The security is privileged'), ('3', 'Government bonds'), ('4', 'Regional bonds'), ('5', 'Central bank bonds'), ('6', 'Corporate bonds'), ('7', 'MFO bonds'), ('8', 'Exchange-traded bonds'), ('9', 'Shares of open MIF'), ('A', 'Shares of interval MIF'), ('B', 'Shares of closed MIF'), ('C', 'Municipal bonds'), ('D', 'Depository receipts'), ('E', 'Securities of exchange investment funds (ETFs)'), ('F', 'Mortgage certificate'), ('G', 'A basket of securities'), ('H', 'Additional list ID'), ('I', 'ETC (commodity instruments)'), ('U', 'Clearing certificates of participation'), ('Q', 'Currency'), ('J', 'A share of stock exchange MIF')], default='1', help_text='The type of security.', max_length=1, null=True, verbose_name='sectype')),
                ('listlevel', models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], default=1, help_text='The listing level.', null=True, verbose_name='listlevel')),
                ('settledate', models.DateField(help_text='Settlement date of the transaction.', null=True, verbose_name='settledate')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'ordering': ('ticker',),
            },
        ),
    ]
