# Generated by Django 5.0.3 on 2024-03-31 09:42

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=18, help_text='The opening price.', max_digits=36, verbose_name='open')),
                ('close', models.DecimalField(decimal_places=18, help_text='The closing price.', max_digits=36, verbose_name='close')),
                ('high', models.DecimalField(decimal_places=18, help_text='The highest price.', max_digits=36, verbose_name='high')),
                ('low', models.DecimalField(decimal_places=18, help_text='The lowest price.', max_digits=36, verbose_name='low')),
                ('value', models.DecimalField(decimal_places=18, help_text='The total value of trades during the candle period.', max_digits=36, verbose_name='value')),
                ('volume', models.DecimalField(decimal_places=18, help_text='The total volume of trades during the candle period.', max_digits=36, verbose_name='volume')),
                ('time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='The time range during which the candlestick represents the trading activity.', verbose_name='time range')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='stocks.stock', verbose_name='stock')),
            ],
            options={
                'verbose_name': 'candle',
                'verbose_name_plural': 'candles',
            },
        ),
    ]
