# Generated by Django 5.0.3 on 2024-03-31 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_candle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'ordering': ('-time_range',), 'verbose_name': 'candle', 'verbose_name_plural': 'candles'},
        ),
        migrations.AlterUniqueTogether(
            name='candle',
            unique_together={('stock', 'time_range')},
        ),
    ]
