# Generated by Django 5.0.3 on 2024-04-30 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='stocks.stock', verbose_name='stock'),
        ),
        migrations.CreateModel(
            name='BlacklistedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_stocks', to='stocks.stock', verbose_name='stock')),
            ],
            options={
                'verbose_name': 'Blacklisted Stock',
                'verbose_name_plural': 'Blacklisted Stocks',
            },
        ),
    ]
