# Generated by Django 5.0.3 on 2024-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_blacklistedstock_stock_alter_candle_time_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricechange',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
